"""empty message

Revision ID: 920380e6b4da
Revises: 
Create Date: 2021-10-19 13:06:01.846774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920380e6b4da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_index('fki_tarea_fk', table_name='tarea')
    op.drop_table('tarea')
    op.drop_index('fki_carpeta_fk', table_name='carpeta')
    op.drop_table('carpeta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpeta',
    sa.Column('id_carpeta', sa.INTEGER(), server_default=sa.text("nextval('carpeta_id_carpeta_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], name='carpeta_fk'),
    sa.PrimaryKeyConstraint('id_carpeta', name='carpeta_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('fki_carpeta_fk', 'carpeta', ['id_usuario'], unique=False)
    op.create_table('tarea',
    sa.Column('id_tarea', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_carpeta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('estado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_carpeta'], ['carpeta.id_carpeta'], name='tarea_fk'),
    sa.PrimaryKeyConstraint('id_tarea', name='tarea_pkey')
    )
    op.create_index('fki_tarea_fk', 'tarea', ['id_carpeta'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey')
    )
    # ### end Alembic commands ###
