"""empty message

Revision ID: 963d69af7c2d
Revises: 920380e6b4da
Create Date: 2021-10-20 01:18:42.943262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963d69af7c2d'
down_revision = '920380e6b4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carpeta', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('fki_carpeta_fk', table_name='carpeta')
    op.alter_column('tarea', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('tarea', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('fki_tarea_fk', table_name='tarea')
    op.alter_column('usuario', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('usuario', 'contraseña',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'contraseña',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('usuario', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index('fki_tarea_fk', 'tarea', ['id_carpeta'], unique=False)
    op.alter_column('tarea', 'estado',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tarea', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index('fki_carpeta_fk', 'carpeta', ['id_usuario'], unique=False)
    op.alter_column('carpeta', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
